# loki/promtail-config.yml

# Configuração do servidor (porta onde o Promtail se expõe, se necessário)
server:
  http_listen_port: 9080
  grpc_listen_port: 0

# Onde o Promtail armazena o seu "progresso"
positions:
  filename: /tmp/positions.yaml

# O alvo para onde "empurrar" os logs (o nosso Loki)
clients:
  - url: http://loki:3100/loki/api/v1/push

# A parte mais importante: O que "raspar" (scrape)?
scrape_configs:
- job_name: system
  # Esta é a mágica:
  docker_sd_configs:
    - host: unix:///var/run/docker.sock # Onde está o Docker
      refresh_interval: 5s
      # Vamos pegar logs de TODOS os containers
      filters:
        - name: label
          values: ["logging=true"] # Vamos ver isto no docker-compose
  
  # Como re-rotular os logs que encontramos:
  relabel_configs:
    # Para cada log de container, crie uma etiqueta 'container'
    - source_labels: ['__meta_docker_container_name']
      regex: '/(.*)'
      target_label: 'container'
    
    # Crie uma etiqueta 'job' a partir do nome do serviço
    - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
      target_label: 'job'